version: 1

#build_arg_defaults:
#  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"

#ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend: |
    RUN yum update -y
    RUN pip3 install --upgrade pip setuptools
  append:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc